country = input('Укажите вашу страну: ')
#print(country)
city = input('Укажите ваш город: ')
#print(city)
street = input('Укажите вашу улицу: ')
#print(street)
house = input('Укажите номер дома: ')
#print(int(house))
print(country, city, street, house)